{
 "title": "Azure PostgreSQL Queries",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "query_current_id", "label": "Query ID" }
  ]
 },
 "panels": [
  {
   "title": "Identify root causes (Use if has accident)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Long-running transactions",
     "type": "table",
     "description": "Long-running transactions can consume CPU resources that can lead to high CPU utilization.",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 1 },
     "targets": [
      {
       "rawSql": "SELECT pid, usename, datname, query, now() - xact_start as duration \nFROM pg_stat_activity  \nWHERE pid <> pg_backend_pid() and state IN ('idle in transaction', 'active') \nORDER BY duration DESC;   "
      }
     ]
    },
    {
     "title": " Identify high I/O utilization",
     "type": "table",
     "description": "Helps identify queries that consume I/O on the server",
     "gridPos": { "h": 7, "w": 13, "x": 11, "y": 1 },
     "targets": [
      {
       "rawSql": "SELECT userid::regrole, dbid, query, calls\nFROM pg_stat_statements \nORDER BY blk_read_time + blk_write_time desc  \nLIMIT 5;"
      }
     ]
    },
    {
     "title": "Total number of connections and number connections by state",
     "type": "bargauge",
     "description": "A large number of connections to the database is also another issue that might lead to increased CPU and memory utilization.\n\n",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 8 },
     "targets": [
      {
       "rawSql": "SELECT state, count(*)  \nFROM  pg_stat_activity   \nWHERE pid <> pg_backend_pid()  \nGROUP BY 1 ORDER BY 1;"
      }
     ]
    },
    {
     "title": "Monitoring vacuum and table stats",
     "type": "table",
     "description": "Keeping table statistics up to date helps improve query performance. Monitor whether regular autovacuuming is being carried out.",
     "gridPos": { "h": 9, "w": 18, "x": 6, "y": 8 },
     "targets": [
      {
       "rawSql": "select schemaname,relname,n_dead_tup,n_live_tup,last_vacuum,last_analyze,last_autovacuum,last_autoanalyze \nfrom pg_stat_all_tables where n_live_tup > 0;"
      }
     ]
    },
    {
     "title": "How much each query in each database uses the CPU",
     "type": "table",
     "description": "It provides a resultset sorted by the mist CPU-intensive queries in descending order",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 17 },
     "targets": [
      {
       "rawSql": "Select pss.userid, pss.dbid, pd.datname as db_name, pss.total_time,\n        pss.calls,\n        pss.mean_time as mean,\n        round((100 * (pss.total_time) / sum ((pss.total_time)::numeric) OVER ()) :: numeric, 2) as cpu_portion_pctg, pss.query\nFrom pg_stat_statements as pss, pg_database as pd\nwhere pd.oid = pss.dbid\norder by pss.total_time\ndesc limit 30;"
      }
     ]
    },
    {
     "title": " Running frequent SQL queries",
     "type": "table",
     "description": "the top frequent PostgreSQL queries run the following SQL query ",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 27 },
     "targets": [
      {
       "rawSql": "with\na as (select dbid, queryid, query, calls s from pg_stat_statements),\nb as (select dbid, queryid, query, calls s from pg_stat_statements, pg_sleep(1))\nselect\n        pd.datname as db_name, \n        substr(a.query, 1, 2048) as the_query, \n        sum(b.s-a.s) as runs_per_second\nfrom a, b, pg_database pd\nwhere \n  a.dbid= b.dbid \nand \n  a.queryid = b.queryid \nand \n  pd.oid=a.dbid\ngroup by 1, 2\norder by 3 desc;"
      }
     ]
    }
   ]
  },
  { "title": "Database Info and Special Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Size of a PostgreSQL Database",
   "type": "bargauge",
   "description": "Provide the size of database postgreSQL in currently",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "MB" } },
   "targets": [
    {
     "rawSql": "SELECT\n  datname as database_name,\n  pg_database_size(datname)/1024/1024 as size\nFROM\n  pg_database\nWHERE\n  datistemplate = false;\n"
    }
   ]
  },
  {
   "title": "Database Cache-Hit Ratios",
   "type": "gauge",
   "description": "The PostgreSQL cache area is known as shared_buffers, which acts as the database layer cache on top of the cache provided by the operating system",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  sum(heap_blks_read) as reads,\n  sum(heap_blks_hit) as hits,\n  ROUND(\n    sum(heap_blks_hit) / (sum(heap_blks_hit) + sum(heap_blks_read)),\n    4\n  ) as hit_ratio\nFROM\n  pg_statio_user_tables;\n"
    }
   ]
  },
  { "title": "Statistic Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Top 10 most of time in total queries last 7 days",
   "type": "piechart",
   "description": "Total time of queries, There one queries give for running on whole system",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select       round(total_time::numeric, 2) as total,\n             calls,\n             round(mean_time::numeric, 2) as mean,\n             stddev_time,\n             query_sql_text as query\nfrom query_store.qs_view\nwhere (now() - start_time) <= interval '7 days'\nand query_sql_text not ilike '%query_store%'\norder by total_time DESC\nlimit 10;"
    }
   ]
  },
  {
   "title": "The 10 slowest queries with over a 1000 calls last 7 days",
   "type": "table",
   "description": "Chart will show the top 10 of slowest queries last 7 days",
   "gridPos": { "h": 10, "w": 15, "x": 9, "y": 12 },
   "targets": [
    {
     "rawSql": "select db_id as database_id, pd.datname, CASE\n           WHEN query_sql_text ILIKE 'SELECT%' OR query_sql_text ILIKE '%\\n%SELECT%' THEN 'SELECT'\n           WHEN query_sql_text ILIKE 'INSERT%' OR query_sql_text ILIKE '%\\n%INSERT%' THEN 'INSERT'\n           WHEN query_sql_text ILIKE 'UPDATE%' OR query_sql_text ILIKE '%\\n%UPDATE%' THEN 'UPDATE'\n           WHEN query_sql_text ILIKE 'DELETE%' OR query_sql_text ILIKE '%\\n%DELETE%' THEN 'DELETE'\n           ELSE 'OTHER'\n       END AS query_type, query_sql_text, calls, (total_time/calls)::integer AS avg_time_ms\nfrom query_store.qs_view, pg_database as pd\nwhere db_id = pd.oid and calls > 1000 and query_sql_text not ILIKE '%query_store%'\nand (now() - start_time) <= interval '7 days'\nORDER BY avg_time_ms DESC\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Total queries running longer than 5 sec last 7 days",
   "type": "gauge",
   "description": "Amounts of queries with running longer than 5 minutes last 7 days",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*)\nFROM pg_stat_activity\nWHERE (now() - pg_stat_activity.query_start) > interval '5 seconds' \nAND (now() - pg_stat_activity.query_start) <= interval '7 days'\nAND datname NOT ILIKE 'azure_sys';"
    }
   ]
  },
  {
   "title": "Detail queries running longer than 5 sec on last 7 days",
   "type": "table",
   "description": "This chart tell us about what queries is running longer than 5 sec on all database.\n\n#### Please use the *query_type* filter on head of table for get type of queries you want.",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT\n  pid,\n  datname as database,\n  user,\n       CASE\n           WHEN query ILIKE 'SELECT%' OR query ILIKE '%\\n%SELECT%' THEN 'SELECT'\n           WHEN query ILIKE 'INSERT%' OR query ILIKE '%\\n%INSERT%' THEN 'INSERT'\n           WHEN query ILIKE 'UPDATE%' OR query ILIKE '%\\n%UPDATE%' THEN 'UPDATE'\n           WHEN query ILIKE 'DELETE%' OR query ILIKE '%\\n%DELETE%' THEN 'DELETE'\n           ELSE 'OTHER'\n       END AS query_type,\n  pg_stat_activity.query_start,\n  now() - pg_stat_activity.query_start AS query_time,\n  query,\n  state,\n  wait_event_type,\n  wait_event\nFROM pg_stat_activity\nWHERE (now() - pg_stat_activity.query_start) > interval '5 seconds' \nAND (now() - pg_stat_activity.query_start) <= interval '7 days'\nAND datname NOT ILIKE 'azure_sys';"
    }
   ]
  },
  { "title": "Live Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Open Connections",
   "type": "bargauge",
   "description": "Querying to Check PostgreSQL Open Connections .You need to consider about:\n\n**backend_type** - *Type of current backend*. Possible types are: \n\n“Client backend\" is basically your normal connection from application. All other connections are special processes that “do stuff\":\n\n- archiver – runs archive_command (or it's equivalent in newer pgs)\n- autovacuum launcher – starts autovacuum workers when it's necessary to vacuum/analyze something\n- background writer – writes data to tables/indexes in the background\n- checkpointer handles checkpoints – basically every now and then writing all modified data to table/index files\n- logical replication launcher – manages processes related to logical replication\n- walwriter – writes changes in data to WAL\n\nAside from these you can also see:\n\n- autovacuum worker – actually does some vacuum/analyze work for autovacuum\n- logical replication worker – works on logical replication\n- parallel worker – special backend started by client backend where query is being processes in parallel\n- startup – applies WAL from somewhere, this is the process that is responsible for recovery and streaming/wal replication\n- walreceiver – receives wal stream from source in streaming replication setups\n- walsender – sends wal via stream to some replica\n\nYou can also see some other types if you use specialized extensions.\n\n*For more detail go to this [link](https://www.depesz.com/2022/07/05/understanding-pg_stat_activity/#:~:text=Last%20column%20is%20backend_type)*\n",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  COUNT(*) as connections,\n  backend_type\nFROM\n  pg_stat_activity\nGROUP BY\n  backend_type\nORDER BY\n  connections DESC"
    }
   ]
  },
  {
   "title": "Total processes of DB",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 5, "x": 7, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*)\n    FROM pg_stat_activity\n    WHERE query NOT ILIKE '%pg_stat_activity%' and datname NOT ILIKE '%azure_sys%' and application_name != '';"
    }
   ]
  },
  {
   "title": "Process in currently of DB",
   "type": "table",
   "description": "This chart tell about the what active is current running. \nSome of information need to consider:\n\n**State** - *Current overall state of this backend*. Possible values are\n\n- active: The backend is executing a query.\n- idle: The backend is waiting for a new client command.\n- idle in transaction: The backend is in a transaction, but is not currently executing a query.\n- idle in transaction (aborted): This state is similar to idle in transaction, except one of the statements in the transaction caused an error.\n- fastpath function call: The backend is executing a fast-path function.\n- disabled: This state is reported if track_activities is disabled in this backend.\n\n*For more detail go to this [link](https://www.postgresql.org/docs/current/monitoring-stats.html#:~:text=Table%C2%A028.13.-,state,-text)*\n\n**Database** - 'some special db you have seen in table chart'\n- *postgres* - A default database you can connect to once your server is created.\n- *azure_maintenance* - This database is used to separate the processes that provide the managed service from user actions. You do not have access to this database.\n- *azure_sys* - A database for the Query Store. This database does not accumulate data when Query Store is off; this is the default setting. For more information, see the [Query Store overview](https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/postgresql/single-server/concepts-query-store.md).",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT datname as Database, pid, application_name, state, query, backend_type\n    FROM pg_stat_activity\n    WHERE query NOT ILIKE '%pg_stat_activity%' and datname NOT ILIKE '%azure_sys%' and application_name != '';"
    }
   ]
  },
  {
   "title": "State of process in DB",
   "type": "barchart",
   "description": "Current infomation about state of process in DB",
   "gridPos": { "h": 7, "w": 7, "x": 4, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT state, COUNT(*) FROM pg_stat_activity  \nWHERE pid <> pg_backend_pid() AND query NOT ILIKE '%pg_stat_activity%' and datname NOT ILIKE '%azure_sys%' and application_name != ''\nGROUP BY 1;"
    }
   ]
  },
  {
   "title": "Application_name on process in DB",
   "type": "bargauge",
   "description": "Currently about the number of application_name in DB. Some situation about the chart:\n- If it not exist `application_name`. The `count` column will represent for it.\n- The chart will focus visuallize the `application_name` connect what database in `currently` process.",
   "gridPos": { "h": 7, "w": 9, "x": 12, "y": 41 },
   "targets": [
    {
     "rawSql": "SELECT application_name, COUNT(*) FROM pg_stat_activity  \nWHERE pid <> pg_backend_pid() and query NOT ILIKE '%pg_stat_activity%' and datname NOT ILIKE '%azure_sys%' and application_name != ''\nGROUP BY 1 ORDER BY 1;"
    }
   ]
  },
  {
   "title": "Connections waiting for a lock",
   "type": "gauge",
   "description": "Number of connection have blocking by lock",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(distinct pid) FROM pg_locks WHERE granted = false;"
    }
   ]
  },
  {
   "title": "Totals queries have been running for longer than a minute",
   "type": "gauge",
   "description": "Lots of long-running queries can cause your database to be slow or non-responsive.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) \nFROM pg_stat_activity \nWHERE state != 'idle' \nAND query_start < (NOW() - INTERVAL '60 seconds');"
    }
   ]
  },
  {
   "title": "Total queries are currently writing to the same table",
   "type": "gauge",
   "description": "Too many write queries to the same (especially large) table can cause lock-contention.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*)  FROM pg_stat_activity\nWHERE state != 'idle'\nAND query NOT ILIKE '%SELECT%'\nAND query ILIKE '%some_big_table%'\nAND query NOT ILIKE '%pg_stat_activity%';"
    }
   ]
  },
  {
   "title": "Querry Searching",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "collapsed": true,
   "panels": [
    {
     "title": "Get query from ID",
     "type": "table",
     "description": "Choose the ID in search box variable for get the query",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 56 },
     "targets": [
      {
       "rawSql": "SELECT query_sql_text FROM query_store.query_texts_view WHERE query_text_id='$query_current_id';\n"
      }
     ]
    }
   ]
  }
 ]
}