{
 "title": "Mongodb Metrics Dashboard",
 "description": "MongoDB Dashboard with Cluster, Replication, cursor, and server metrics using Mongodb Exporter by percona",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Cluster Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "MongoService UP",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_up{instance=\"mongodb-exporter-prometheus-mongodb-exporter.monitoring.svc:9216\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Mongodb Uptime",
   "type": "stat",
   "description": "Mongodb Service Uptime in hours",
   "gridPos": { "h": 8, "w": 5, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_members_uptime{member_state=\"PRIMARY\",instance=\"mongodb-exporter-prometheus-mongodb-exporter.monitoring.svc:9216\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Current Connections",
   "type": "stat",
   "description": "The number of incoming connections from clients to the database server. This number includes the current shell session. Consider the value of connections.available to add more context to this datum.",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_ss_connections{conn_type=\"current\", instance=\"mongodb-exporter-prometheus-mongodb-exporter.monitoring.svc:9216\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Created Connections",
   "type": "stat",
   "description": "Count of all incoming connections created to the server. This number includes connections that have since closed.",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_ss_connections{conn_type=\"totalCreated\", instance=\"mongodb-exporter-prometheus-mongodb-exporter.monitoring.svc:9216\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Available Connections",
   "type": "stat",
   "description": "The number of unused incoming connections available. Consider this value in combination with the value of connections.current to understand the connection load on the database, and the UNIX ulimit Settings document for more information about system thresholds on available connections.",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_ss_connections{conn_type=\"available\", instance=\"mongodb-exporter-prometheus-mongodb-exporter.monitoring.svc:9216\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "stat",
   "description": "The number of active client connections to the server. Active client connections refers to client connections that currently have operations in progress.",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_ss_connections{conn_type=\"available\",instance=\"mongodb-exporter-prometheus-mongodb-exporter.monitoring.svc:9216\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "opcounters",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 9 },
   "options": {
    "content": "A document that reports on database operations by type since the mongod instance last started. These numbers will grow over time until next restart. Analyze these values over time to track database utilization."
   }
  },
  {
   "title": "Received Insert Operations",
   "type": "timeseries",
   "description": "The total number of insert operations received since the mongod instance last started.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "mongodb_ss_opcounters{legacy_op_type=\"insert\",instance=\"mongodb-exporter-prometheus-mongodb-exporter.monitoring.svc:9216\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Received Update Operations",
   "type": "timeseries",
   "description": "The total number of update operations received since the mongod instance last started.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "mongodb_ss_opcounters{legacy_op_type=\"update\",instance=\"mongodb-exporter-prometheus-mongodb-exporter.monitoring.svc:9216\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Received Command Operations",
   "type": "timeseries",
   "description": "The total number of commands issued to the database since the mongod instance last started.\n\nopcounters.command counts all commands except the write commands: insert, update, and delete.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "mongodb_ss_opcounters{legacy_op_type=\"command\",instance=\"mongodb-exporter-prometheus-mongodb-exporter.monitoring.svc:9216\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Received Queries",
   "type": "timeseries",
   "description": "The total number of queries received since the mongod instance last started.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "mongodb_ss_opcounters{legacy_op_type=\"query\",instance=\"mongodb-exporter-prometheus-mongodb-exporter.monitoring.svc:9216\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Received Delete Operations",
   "type": "timeseries",
   "description": "The total number of delete operations since the mongod instance last started.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "mongodb_ss_opcounters{legacy_op_type=\"delete\",instance=\"mongodb-exporter-prometheus-mongodb-exporter.monitoring.svc:9216\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Received getMore Operations",
   "type": "timeseries",
   "description": "The total number of getMore operations since the mongod instance last started. This counter can be high even if the query count is low. Secondary nodes send getMore operations as part of the replication process.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "mongodb_ss_opcounters{legacy_op_type=\"getmore\",instance=\"mongodb-exporter-prometheus-mongodb-exporter.monitoring.svc:9216\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Collections/DB",
   "type": "bargauge",
   "description": "Number of collections in the database.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_dbstats_collections{instance=\"mongodb-exporter-prometheus-mongodb-exporter.monitoring.svc:9216\"}",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Total Indexs/DB",
   "type": "bargauge",
   "description": "Total number of indexes across all collections in the database.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_dbstats_indexes{instance=\"mongodb-exporter-prometheus-mongodb-exporter.monitoring.svc:9216\"}",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Total Views/DB",
   "type": "bargauge",
   "description": "Number of views in the database.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_dbstats_views{instance=\"mongodb-exporter-prometheus-mongodb-exporter.monitoring.svc:9216\"}",
     "legendFormat": "{{database}}"
    }
   ]
  },
  {
   "title": "Allocated Storage to Collections in DB",
   "type": "bargauge",
   "description": "Sum of the space allocated to all collections in the database for document storage, including free space.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_dbstats_storageSize{instance=\"mongodb-exporter-prometheus-mongodb-exporter.monitoring.svc:9216\"}",
     "legendFormat": "{{database}} "
    }
   ]
  },
  {
   "title": "Allocated Storage to Indexs in DB",
   "type": "bargauge",
   "description": "Sum of the space allocated to all indexes in the database, including free index space.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_dbstats_indexSize{instance=\"mongodb-exporter-prometheus-mongodb-exporter.monitoring.svc:9216\"}",
     "legendFormat": "{{database}}"
    }
   ]
  },
  { "title": "Replication Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "OPLog Size",
   "type": "timeseries",
   "description": "The oplog (operations log) is a special capped collection that keeps a rolling record of all operations that modify the data stored in your databases.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "mongodb_oplog_stats_size{instance=\"mongodb-exporter-prometheus-mongodb-exporter.monitoring.svc:9216\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Oplog FreeStorageSize",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "expr": "mongodb_oplog_stats_freeStorageSize{instance=\"mongodb-exporter-prometheus-mongodb-exporter.monitoring.svc:9216\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 10 MongoDB Commands  by count",
     "type": "bargauge",
     "description": "Chart using top queries about top 10 command with highest counts",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 55 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (collection, database) (topk(10, mongodb_top_commands_count))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Top 10 MongoDB Commands by times",
     "type": "bargauge",
     "description": "Chart about the top command with most of time queries in interval of Mongodb ",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 55 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (collection, database) (topk(10, mongodb_top_commands_time))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Top 10 Getmore Queries by counts",
     "type": "bargauge",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 55 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (collection,database) (topk(10, mongodb_top_getmore_count))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Top 10 Getmore Queries by times",
     "type": "bargauge",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 55 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (collection,database) (topk(10, mongodb_top_getmore_time))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Top 10 Insert Queries by counts",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 64 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (collection,database) (topk(10, mongodb_top_insert_count))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Top 10 Insert Queries by times",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 64 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (collection, database) (topk(10, mongodb_top_insert_time))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Top 10 Update Queries by counts",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 64 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (collection, database) (topk(10, mongodb_top_update_count))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Top 10 Update Queries by times",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 64 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (collection, database) (topk(10, mongodb_top_update_time))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Top 10 Remove Queries by counts",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 72 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (collection, database) (topk(10, mongodb_top_remove_count))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Top 10 Remove Queries by times",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 72 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (collection, database) (topk(10, mongodb_top_remove_time))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Top 10  Queries by counts",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 72 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (collection, database) (topk(10, mongodb_top_queries_count))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Top 10 Queries by times",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 72 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (collection, database) (topk(10, mongodb_top_queries_time))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Top 10 readLock by counts",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 80 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (collection, database) (topk(10, mongodb_top_readLock_count))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Top 10 readLock by times",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 80 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (collection, database) (topk(10, mongodb_top_readLock_time))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Top 10 WriteLock by counts",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 80 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (collection, database) (topk(10, mongodb_top_writeLock_count))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Top 10 WriteLock by times",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 80 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg by (collection, database) (topk(10, mongodb_top_writeLock_time))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Cursor Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cursor Timeout",
     "type": "timeseries",
     "description": "Cursor is a pointer, and using this pointer we can access the document. cursor.timeOut property was updated incrementally, and connections that died without closing the cursor. The consequence is that it will remain open on the server and consume memory unless it is reaped by the default MongoDB setting.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
     "targets": [
      {
       "expr": "mongodb_ss_metrics_cursor_timedOut{instance=\"mongodb-exporter-prometheus-mongodb-exporter.monitoring.svc:9216\"}",
       "legendFormat": "{{instance}} - {{rs_nm}}"
      }
     ]
    },
    {
     "title": "Cursor totalOpened",
     "type": "timeseries",
     "description": "Number of cursors currently opened by MongoDB for clients",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
     "targets": [
      {
       "expr": "mongodb_ss_metrics_cursor_totalOpened{instance=\"mongodb-exporter-prometheus-mongodb-exporter.monitoring.svc:9216\"}",
       "legendFormat": "{{instance}} - {{rs_nm}}"
      }
     ]
    }
   ]
  }
 ]
}